### ISSUE TITLE
🍎 Add ARM64 macOS (Apple Silicon) Support

### ISSUE THREAD

**Issue by kengggg** [opendream/vanityssh-rust#11]
# 🍎 Add ARM64 macOS (Apple Silicon) Support

## Overview
Implement native ARM64 macOS support for Apple Silicon users, providing optimized performance on M1/M2/M3/M4 Macs with proper cross-compilation and testing.

### 1. ARM64 macOS Target Setup
- [ ] Add `aarch64-apple-darwin` target to CI matrix
- [ ] Configure ARM64 macOS runners (GitHub native ARM64)
- [ ] Set up cross-compilation from x86_64 to ARM64
- [ ] Test ARM64 builds on actual Apple Silicon hardware

### 2. Build Configuration
- [ ] Update Cargo.toml with ARM64-specific optimizations
- [ ] Configure ARM64-specific compiler flags
- [ ] Optimize for Apple Silicon performance characteristics
- [ ] Enable ARM64 NEON optimizations where applicable

### 3. CI Integration
- [ ] Add ARM64 macOS to build matrix
- [ ] Set up ARM64-specific testing pipeline
- [ ] Configure artifact generation for ARM64 binaries
- [ ] Add universal binary support (x86_64 + ARM64)

### 4. Performance Optimization
- [ ] ARM64-specific performance tuning
- [ ] Benchmark ARM64 vs x86_64 performance
- [ ] Optimize for Apple Silicon memory architecture
- [ ] Test multi-threading performance on Apple Silicon

## Acceptance Criteria
- [ ] ARM64 macOS binaries build successfully in CI
- [ ] Native ARM64 performance matches or exceeds x86_64
- [ ] Universal binaries work on both Intel and Apple Silicon
- [ ] ARM64 binaries pass all tests
- [ ] Performance benchmarks validate optimization

### Cargo.toml Updates
```toml
[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=apple-m1"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
# ARM64-specific optimizations
```

### CI Matrix Addition
```yaml
strategy:
  matrix:
    include:
      # Existing targets...
      - os: macos-latest
        target: aarch64-apple-darwin
        arch: arm64
        rust-version: stable
```

### Cross-compilation Setup
```yaml
- name: Install ARM64 target
  run: rustup target add aarch64-apple-darwin

- name: Build ARM64 binary
  run: cargo build --release --target aarch64-apple-darwin
```

### Universal Binary Creation
```bash
# Create universal binary combining x86_64 and ARM64
lipo -create \
  target/x86_64-apple-darwin/release/vanityssh-rust \
  target/aarch64-apple-darwin/release/vanityssh-rust \
  -output target/universal/vanityssh-rust
```

### 1. Build Testing
- [ ] Cross-compilation from x86_64 macOS
- [ ] Native compilation on ARM64 macOS runners
- [ ] Universal binary creation and validation

### 2. Performance Testing
- [ ] Key generation speed comparison (ARM64 vs x86_64)
- [ ] Memory usage patterns on Apple Silicon
- [ ] Multi-threading scaling on Apple Silicon cores
- [ ] Regex performance validation

### 3. Compatibility Testing
- [ ] macOS version compatibility (11.0+)
- [ ] Apple Silicon-specific features
- [ ] Rosetta 2 fallback testing
- [ ] Code signing validation

## Expected Performance Gains
- **15-30% faster** key generation on Apple Silicon
- **Better power efficiency** for battery-powered devices
- **Native threading** optimized for Apple Silicon architecture
- **Memory bandwidth** advantages of unified memory

## Platform-Specific Considerations
- **Minimum macOS:** 11.0 (Big Sur) for native ARM64
- **Code signing:** May require developer certificates
- **Notarization:** For distribution outside Mac App Store
- **Universal binaries:** Larger file size but better compatibility

## Timeline
**Estimate:** 3-4 days  
**Priority:** High (Apple Silicon adoption is significant)  
**Phase:** 2

## Labels
`enhancement`, `platform-macos`, `phase-2`, `priority-high`, `ci/cd`, `architecture`

## Dependencies
- Phase 1 completion (enhanced CI foundation)
- Access to ARM64 macOS runners or hardware

---
*Part of Phase 2: Multi-Architecture Support - Critical for Apple Silicon users*
